name: mirrorchyan_release_note

on:
  workflow_dispatch:
  release:
    types: [edited]

jobs:
  mirrorchyan:
    runs-on: macos-latest

    steps:
      - id: uploading
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: BAAS

          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          owner: pur1fying
          repo: blue_archive_auto_script
          github_token: ${{ secrets.GITHUB_TOKEN }}
